name: 'Pawn Compile Action'
description: 'Download the Zeex Pawn compiler and compile Pawn (.pwn) files.'
branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  source:
    description: 'Path to the Pawn (.pwn) file to compile.'
    required: true

  include-path:
    description: 'Path to the include directory.'
    required: false
    default: 'pawno/include'

  version:
    description: 'Zeex Pawn compiler version.'
    required: false
    default: '3.10.10'

  args:
    description: 'Additional arguments passed to the compiler.'
    required: false

runs:
  using: 'composite'
  steps:

    - name: Cache Pawn Compiler
      id: cache-pawn-compiler
      uses: actions/cache@v5
      with:
        path: ./pawn-compiler
        key: ${{ runner.os }}-pawn-compiler-${{ inputs.version }}

    - name: Download Pawn Compiler
      if: steps.cache-pawn-compiler.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ./pawn-compiler
        wget -q https://github.com/pawn-lang/compiler/releases/download/v${{ inputs.version }}/pawnc-${{ inputs.version }}-linux.tar.gz
        tar -xzf pawnc-${{ inputs.version }}-linux.tar.gz -C ./pawn-compiler --strip-components=1

    - name: Install Pawn Compiler
      shell: bash
      run: |
        sudo cp ./pawn-compiler/bin/pawncc /usr/local/bin/
        sudo chmod +x /usr/local/bin/pawncc

        sudo cp ./pawn-compiler/lib/libpawnc.so /usr/local/lib/
        sudo ldconfig

    - name: Compile Pawn File
      shell: bash
      run: |
        pawncc ${{ inputs.source }} -i"${{ inputs.include-path }}" ${{ inputs.args }}
